version: "3.9"
  
services:
  ####################################################
  # MySQL                                            #
  ####################################################
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1111
      ME_CONFIG_MONGODB_URL: mongodb://root:1111@mongo:27017/

  graphql-server:
    image: node:18-alpine
    working_dir: /app
    command: yarn start:dev
    volumes: 
      - "./graphql-server/:/app/"
    environment:
      MONGO_CONNECTION_STRING: "mongodb://root:1111@mongo:27017"
      MONGO_DATABASE: "categories"
      NODE_ENV: "development"
      APP_PORT: "5000"
    ports:
      - 5000:5000
    depends_on:
      - mongo

  web-application:
    image: node:18-alpine
    working_dir: /app
    command: yarn start
    volumes: 
      - "./web-application/:/app/"
    ports:
      - 3000:3000
    depends_on:
      - graphql-server
